### ISSUE TITLE
Add label to a geojson Feature

### ISSUE THREAD

**Issue by sylvain258** [mapbox/mapbox-maps-android#1029]
Hello,

I don't know if it's here I have to post my request. I would like to know how add label to a geojson feature. I try with TextAnchor and Circle Annotation but this doesn't complete.

I defined a style and my geojson source and the symbology. 

This is my code :

```
mapView?.getMapboxMap()?.loadStyle(
            style(Style.OUTDOORS){
                +geoJsonSource(id="dev_cpa") {
                    url("monfichier.geojson")
                }
                +circleLayer("cpa_dev", "dev_cpa") {
                    circleRadius(6.0)
                    circleColor("#FF9800")
                    circleOpacity(0.8)
                    circleStrokeColor(Color.BLACK)
                    circleStrokeWidth(1.0)
                }

            }
        )
```

Thank you very much for your help

Sylvain

**Comment by ZiZasaurus** [comment]
@sylvain258 to add a label to a geojson feature you would want to use either a SymbolLayer or a Point Annotation, rather than a CircleLayer. Please take a look at one of our examples demonstrating the symbol layer [here](https://github.com/mapbox/mapbox-maps-android/blob/60387a03112ad38aa50fe3f8402a167f14bea683/app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt). I've also included a snippet below demonstrating how to add text to a point annotation. 

```
var pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
    .withPoint(Point.fromLngLat(lon_center, lat_center))
    .withTextField("here is our text")
    .withTextColor("#000000")

pointAnnotationManager.create(pointAnnotationOptions)
```
