### ISSUE TITLE
Android 12 approximate user location

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-android#1046]
## New Feature

In Android 12 user can allow app to get only approximate user location. Currently Mapbox PermissionsManager seems to handle approximate location same way as precise location. iOS 14 has similar feature and it works fine on iOS Mapbox. Add support for handling approximate location to Android Mapbox also. Example app would be nice to have also.

## Why
Currently it seems to require custom location permissions handling to implement this on Android 12. Would be nice if this had better support built into Mapbox SDK similar to iOS Mapbox SDK.

**Comment by ZiZasaurus** [comment]
@ittna permission handling to access the user location is fully handled by the developer regardless of whether it's approximate or fine location.

**Comment by ittna** [comment]
Maybe I'm missing something but there is `com.mapbox.android.core.permissions.PermissionsManager`

If you ask location permission using `permissionsManager.requestLocationPermissions(activity)` and then on Android 12 user gives only permission to approximate location. `PermissionsManager.areLocationPermissionsGranted(activity)` returns `true`. I mean is there some way to check with `PermissionsManager` whether user gave approximate or fine location.

**Comment by kiryldz** [comment]
@ittna indeed our default [`LocationProviderImpl`](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt) relies on components from `com.mapbox.mapboxsdk:mapbox-android-core` dependency that does perhaps does not have full support for Android 12 approximate location (I did not check it deeply).

However as per design Mapbox location component plugin is pretty easily customizable. In your particular case you could provide your own location provider instance and grant all needed permissions on your app side. You could find an example of providing custom location provider e.g. in this [activity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt).

I'll open a ticket though to update `com.mapbox.mapboxsdk:mapbox-android-core` so that our default implementation will also handle location permissions better but it will not be a highest priority I believe.

Please re-open this issue if you'll have more questions.
