### ISSUE TITLE
Official support for Jetpack Compose

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#129]
This comes in a great combination with Mapbox v10's Kotlin first design.

**Comment by daniel-j-h** [comment]
Hey folks :wave: I played around with [Compose](https://developer.android.com/jetpack/compose) to build an app and ran into this exact issue, too. The main question is how to adapt the imperative apis the map provides for a declarative world modern user interfaces are moving towards.

Ideally we'd have a declarative map wrapper taking a viewport from the parent component (composable), then
- the map component is stateless and its appearance only gets controlled by the properties passed in, and
- the viewport property acts as a single source of truth for the map's appearance throughout the app

The most basic use-case would then look like this on the call site

```kotlin
val (viewport, setViewport) = remember { mutableStateOf(initialViewport) }

Map(viewport = viewport, onViewportChange = setViewport)
```

I've built a declarative wrapper around the map for my own use case; you can find a very basic version here

https://gist.github.com/daniel-j-h/cd88b6cdf54e86bffed2bc440cbbb751


Side note: this is similar to https://github.com/visgl/react-map-gl (are we full circle yet :upside_down_face:) and it would be great to have support within this project, instead of smaller wrapper projects (like react-map-gl) popping up.

**Comment by VincentJoshuaET** [comment]
Compose is now stable

**Comment by tialawllol** [comment]
https://github.com/googlemaps/android-maps-compose

Take a look at this and copy/paste their solution ;-)

**Comment by dellisd** [comment]
I've [played around](https://github.com/dellisd/reroute/tree/master/web/src/jsMain/kotlin/io/github/dellisd/reroute/map/compose) with building a Compose for Web wrapper around mapbox-gl-js. The implementation still needs work, but I think the general compose-level API design is decent. 

The map is controlled through a [`MapboxState` object](https://github.com/dellisd/reroute/blob/master/web/src/jsMain/kotlin/io/github/dellisd/reroute/map/compose/MapboxMap.kt#L199) which, for example, [allows the different camera methods to be called](https://github.com/dellisd/reroute/blob/master/web/src/jsMain/kotlin/io/github/dellisd/reroute/map/MapDemo.kt#L42). The map's sources, layers, and styles are implemented as a separate compose tree in order to properly integrate with the Map's separate lifecycle and also maintains a nice DSL for constructing the map.

I haven't tried yet, but I'm sure the same kind of thing could be implemented with Jetpack Compose and the Android Maps SDK.

**Comment by warting** [comment]
Any official updates regarding this?

**Comment by yunikkk** [comment]
> Any official updates regarding this?

Hi, no updates at the moment.

**Comment by VincentJoshuaET** [comment]
Will this ever be possible to have a a Mapbox application without any XML layouts and `AndroidView`s?

**Comment by daniel-j-h** [comment]
There is a prototype for a compose interface here
- https://github.com/mapbox/mapbox-maps-android/pull/1443

It looks like it hasn't moved in the last four months, tho.

**Comment by patrick-fitzgerald** [comment]
Looking forward to seeing it being supported. Is there any timeline on official support for Jetpack Compose?

**Comment by TheScriptan** [comment]
Waiting for the official support too!

**Comment by Alec-Bailey** [comment]
We are also waiting for an update on this. Otherwise, we'll have to move on to another platform.

**Comment by aabolfazl** [comment]
Is there any official to-do list or features backlog for the Jetpack Compose support?

**Comment by JonasVautherin** [comment]
It is not the official support, but @RomanBapst and I have been working on a small Jetpack Compose layer for Mapbox (and MapLibre) called [ramani-maps](https://github.com/ramani-maps/ramani-maps). It is still fairly new, and we still have to solve some issues with Mapbox (e.g. [this one](https://github.com/mapbox/mapbox-maps-android/issues/2115)).

For now we have only added features that we use ourselves, and we hope that it may be useful for others. We want to keep adding features steadily, and obviously we are open to contributions.

Some people here mentioned having to move to another platform if Compose doesn't come to Mapbox, so we hope that maybe this helps bridging the gap.

The project is available on GitHub: https://github.com/ramani-maps/ramani-maps

**Comment by pengdev** [comment]
Thanks for your patience. We're thrilled to unveil our first official Jetpack Compose Extension, now available for [public preview](https://github.com/mapbox/mapbox-maps-android/releases/tag/extension-compose-v0.1.0). Your feedback is invaluable to us. Please share your thoughts so we can enhance the experience for everyone. Thank you!

**Comment by kiryldz** [comment]
Closing this issue for now, please feel free to open any Jetpack Compose related issues here with label `compose`.
