### ISSUE TITLE
Detecting malware after including Mapbox SDK

### ISSUE THREAD

**Issue by karthisamyxplora** [mapbox/mapbox-maps-android#1380]
## Environment

- Android OS version: Android 12
- Devices affected: Samsung A53S, S22, 
- Maps SDK Version: com.mapbox.maps:android:10.4.4

## Observed behavior and steps to reproduce
Go to phone settings under Battery and Device care enable Device protection and install the application it detects as Malware

![PXL_20220519_104537114 MP](https://user-images.githubusercontent.com/74605412/169994955-6b542201-b2df-4f0f-9cbc-332743ca6b92.jpg)
![PXL_20220519_104538782 MP](https://user-images.githubusercontent.com/74605412/169994980-43cf407c-1850-4b35-9a2f-a2b12f659d1a.jpg)
![PXL_20220519_104645669 MP](https://user-images.githubusercontent.com/74605412/169995013-f83f8585-d011-4b4a-b273-4f6b8467ff57.jpg)
![PXL_20220519_104711693 MP](https://user-images.githubusercontent.com/74605412/169995033-8ba8e001-fde3-450e-8359-d0e8f56cee60.jpg)

## Expected behavior
It shouldn't detect as malware

**Comment by ank27** [comment]
@karthisamyxplora Could you provide some more information on
- Are you using any other library / sdks?
- Is there any code / permissions that the app is using which could detect it as a malware?
- How are you installing the apk (if you are just downloading and installing from file manager, it could be that the samsung protection checks if the apk is signed or not. If the apk is not signed that could be the reason since this is how generally device protection works) 

we have other samsung models in-house and it doesn't give any malware error when testing the sdk. It could also be a false positive from samsung/macAfee side. So make sure to install the signed apk and if the error still persists, you can further notify this to manufacturer device protection team, they could help resolve this error.

**Comment by karthisamyxplora** [comment]
Hi,

I have tested in signed apk with mapbox sdk only and able to detect
malware, when I remove Mapbox SDK and install the app it's
successfully installed.

Even though I have a couple of devices which are not detecting Malware,
it's only specific to the device. I have tested using Samsung test Lab
devices Samsung A53S when I install on that I am able to get that. Today I
got a report that Samsung S22 is also having the same issue. But I have not
tested S22.

I don't think we have to report to Samsung until there is some strong
evidence.

Thanks and Regards,
Karthisamy

**Comment by karthisamyxplora** [comment]
Hi,

May I know if there is any permission used in the Mapbox SDK, if so could
you please share with me those permissions?

**Comment by ank27** [comment]
> Even though I have a couple of devices that are not detecting Malware,
> it's only specific to the device.
> 

@karthisamyxplora Yeah, we have tested this with a couple of in-house devices too, it doesn't give any warning of malware. So this could be specific to certain devices only. Also, since the same library version are used across different devices to test and in some of them, it's not detecting malware, I am thinking this could be false positive detection from the security software.

> May I know if there is any permission used in the Mapbox SDK

Below are the permissions that you can see in the manifest-merger file when you build the app with just Mapbox SDK.
```
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" /> 
    <uses-permission
        android:name="android.permission.GET_TASKS"
        android:maxSdkVersion="20" />
```
All these permissions are fairly safe. although we can see that `GET_TASKS` permission is deprecated and is still used, we have removed this permission mentioned in the issue ticket [here](https://github.com/mapbox/mapbox-events-android/issues/557) and fixed it in [pr](https://github.com/mapbox/mapbox-events-android/pull/559) but unfortunately, it's not released yet. 

It could be possible that device protection is flagging use of this permission as malware. Could you maybe try to remove the permission from manifest and see if it is still flagged as malware?

Add below line to the manifest.xml of your app and build the signed apk again

```
<uses-permission android:name="android.permission.GET_TASKS" tools:node="remove" />
```

Let me know if this works, or you could remove all the permissions that are used by Mapbox SDK and check if it is still detected as malware.

**Comment by karthisamyxplora** [comment]
Hi,

<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />

This permission is the main cause of detecting the malware, please review
this permission usage and let me know can you remove this or not?

Is it possible to remove this and include Mapbox lib and then I can test it?

**Comment by karthisamyxplora** [comment]
For your information please use Samsung test Lab for this test you can find
Samsung Galaxy A53 device where I got malware.

**Comment by karthisamyxplora** [comment]
Same issue we had in our application before merging mapbox SDK, we removed
this permission.

**Comment by ank27** [comment]
hey @karthisamyxplora. we figured this permission is not in use anymore. we have a pr merged to remove the permission and it will be available in future release. 
In meantime, you can remove this permission from manifest using 
`<uses-permission android:name="android.permission. CHANGE_NETWORK_STATE" tools:node="remove" />`, this will solve the issue at your end. 

Let me know if you have more issues.

**Comment by karthisamyxplora** [comment]
That’s really cool, I will update and test get back to you if any issues

Thanks and Regards,
Karthisamy

**Comment by ZiZasaurus** [comment]
@karthisamyxplora, closing this but please feel free to reopen if the issue resurfaces.
