### ISSUE TITLE
Performance is laggier when a high amount of layers are shown compared to iOS

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#1449]
## Environment

- Android OS version: Android 12
- Devices affected: Samsung Galaxy S20+, Samsung Galaxy Tab A8, all Android devices
- Maps SDK Version: 10.6.0

## Observed behavior and steps to reproduce

I think it looks worse on the real device compared to the screen recording but here's a comparison.
I did not change the default mapbox_mapSurface attribute, so it is still surface_view.

I also noticed that it's using a high amount of memory, which is probably the reason this happens. How different is your implementation on iOS?

The videos were screen recorded at the same quality; I just had to compress it to be able to upload them.

https://user-images.githubusercontent.com/19756326/175061603-daf6046d-230a-4f94-aa6e-c93a6ef6969f.mov

https://user-images.githubusercontent.com/19756326/175061720-5e4d866c-534d-4519-8450-6529c4b21f89.mov

## Expected behavior

I hope you improve the perfomance when compared to iOS.

## Notes / preliminary analysis

Eventually this will reach more than 20,000 points. Is there a way to optimize this? I'm fetching the data from a Couchbase database synced to our server and I manually construct the Feature objects from each Couchbase document.

I tried to zoom into the map and it does not lag as bad when zoomed out.

Clustering is disabled on both platforms. But the performance is worse on Android.

**Comment by VincentJoshuaET** [comment]
Eventually this will reach more than 20,000 points. Is there a way to optimize this? I'm fetching the data from a Couchbase database synced to our server and I manually construct the Feature objects from each Couchbase document.

**Comment by tobrun** [comment]
> Eventually this will reach more than 20,000 points. Is there a way to optimize this?

It looks like your are processing all the data client side and at runtime adding more data to the map. 

This amount of scale of 20000 , needs to be solved differently. First optimization is doing this on the backend side, the more work you can remove from the client, the better the user experience. The second optimization is how you organize that data, instead of using GeoJSON objects and manually creating new data entries. You can tile your data in to vector tiles and have your backend serve these. This way you are replicating how we show data at scale with our default maps. Third optimization you can take is to decouple the static and dynamic data, ideally you handle as much of this data on the backend but if needed you can enrich your static data on the client side with using feature state APIs. This allows to add data to your vector tiles at runtime. 

You don't need to build all this backend infrastructure yourself, Mapbox offers some services for you to get this to work:
 -  https://www.mapbox.com/mts

**Comment by VincentJoshuaET** [comment]
Why does it perform much better in iOS though?

**Comment by kiryldz** [comment]
Stale, outdated. Performance should be better (at least not worth) with each new version of the SDK, please check the latest version. Also both Android / iOS implementation code would be useful to understand why Android behaves so much worse.
