### ISSUE TITLE
Missing getProjection() function in V 10

### ISSUE THREAD

**Issue by DizparcTim** [mapbox/mapbox-maps-android#1470]
Hello,

I wonder if there is a plan to implement the getProjection() ( mapboxMap.getProjection().fromScreenLocation ) function in V.10. 
Used to catch touch events and draw an area like this guide shows: 
https://docs.mapbox.com/android/legacy/maps/examples/finger-draw-query/

I have not found any way to get the same functionality in version 10, am I missing something or does it not exist? 
If it doesn't exist, is it in the pipeline to add something to support this feature in the future?

**Comment by DizparcTim** [comment]
Either I'm missing something or that does not resolve my problem, or answerer the question I asked.

I want to add a line on the app screen when the user is drawing. 
From the old documentation I found this:
```
LatLng latLngTouchCoordinate = mapboxMap.getProjection().fromScreenLocation(
new PointF(motionEvent.getX(), motionEvent.getY()));
 
Point screenTouchPoint = Point.fromLngLat(latLngTouchCoordinate.getLongitude(),
latLngTouchCoordinate.getLatitude());
```
But I cant really find how to get the method "fromScreenLocation" or any other method where I get the coordinates from a user drawing on the screen.

**Comment by ank27** [comment]
@DizparcTim In order to get coordinate from the screen pixel in v10, you can use
`mapboxMap.coordinateForPixel(pixel: ScreenCoordinate)` or `mapboxMap.coordinatesForPixels(pixels: List<ScreenCoordinate>)`. [here is the method definition](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/main/java/com/mapbox/maps/MapboxMap.kt#L777-L813).

in v10 `getProjection().fromScreenLocation` is replaced by `coordinateForPixel` method. 

Let me know if this solves your query.

**Comment by DizparcTim** [comment]
Thanks, that solves my issue!

**Comment by DizparcTim** [comment]
Thanks that solves my issue!
