### ISSUE TITLE
`OnCameraChangeListener` is invoked on the render thread

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#157]
## Environment
- Maps SDK Version: 10.0.0-beta.15

## Observed behavior and steps to reproduce

`OnCameraChangeListener` is called on the `MapboxRenderThread`.

## Expected behavior

`OnCameraChangeListener` is called on the main thread.

## Notes / preliminary analysis

This is a breaking change that was introduced somewhere between beta.13 and beta.15. Is it the desired behavior @mapbox/maps-android? Looks a little bit surprising.

**Comment by kiryldz** [comment]
@LukasPaczos - it's desired behaviour.
Generally I'd say that 99% calls should happen from main thread but strictly speaking it is now called on any thread that core finds suitable 😄 
That was done in order to emit all animation related events in correct order, previously that callback was put to handler of main thread which could result in having several `OnCameraChangeListener` updates __after__ animation has ended.
It is now user responsibility to post it to main thread if it's required.
PR for reference - https://github.com/mapbox/mapbox-maps-android/pull/125

Closing for now, feel free to open if any questions would appear.
