### ISSUE TITLE
MapView visibility not working as expected

### ISSUE THREAD

**Issue by benferris-tl** [mapbox/mapbox-maps-android#1570]
## Environment

- Android OS version: 12
- Devices affected:
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

I'm working with a layout that contains two MapViews and toggles their visibilities to display one at a time. I've noticed that when a MapView's visibility is set to `invisible` or `gone` in the layout file, it does not appear when it is later set to `visible`. Also, if both maps are initially `visible` and one is subsequently set to `invisible` or `gone`, when the activity is stopped and started any part of the hidden map that overlaps another visible MapView becomes visible.

## Expected behavior

Maps that are `invisible` or `gone` should not be visible. Maps should become visible when their visibility is set to `visible`.

## Additional links and references

[Visibility issue](https://drive.google.com/file/d/1YeGO-w8rAoDv1s5dapux_JtifMCrpTzk/view?usp=sharing), map on the right is initially `gone`

[Overlap visibility issue](https://drive.google.com/file/d/1jzjgb8HCRfQaJaR4rrVNPlAnhfdRMEwn/view?usp=sharing)

**Comment by kiryldz** [comment]
@benferris-tl could you please try to configure both map views as 
```
mapbox:mapbox_mapSurface="texture_view"
```
in xml layout file and see if it will help?

**Comment by benferris-tl** [comment]
@kiryldz That seems to prevent the overlap issue but I still see the other issue where the map never appears if it was not initially `visible`.

**Comment by kiryldz** [comment]
> @kiryldz That seems to prevent the overlap issue but I still see the other issue where the map never appears if it was not initially `visible`.

Does moving the map makes it visible?

**Comment by benferris-tl** [comment]
> Does moving the map makes it visible?

No, it behaves the same way as in the first video, you move it and change the zoom and see the scale indicator change but the rest remains blank.

**Comment by kiryldz** [comment]
@benferris-tl yeah, I could reproduce it. I did spend a bit of time trying to think of workaround however nothing came to my mind yet. I'll create an internal ticket and we'll look deeper into that.

**Comment by kiryldz** [comment]
@benferris-tl after looking into it a bit deeper it seems that if initially `TextureView` or `SurfaceView` was invisible / gone (which happens when you create `MapView` as invisible / gone) - then no rendering will happen even if you'll make it visible again later on programatically (described e.g. [here](https://stackoverflow.com/a/26350949) and in several other places).

I could imagine that refactoring could happen in our codebase to actually initialize renderer and native part lazily based on initial visibility of the `MapView` but it's pretty error-prone and I doubt we'll be doing this. 

As potential workaround for now I could just suggest to actually create both MapView's in your code as visible in xml (and use `texture_view` mode if you need overlaps) and mark one of them invisible / gone immediately in code - at least on my device MapView that is desired to be invisible does not even appear (and that's equivalent to actually marking one of the views invisible / gone in xml). Sample code:

```kotlin
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    // create as visible by default
    val mapView = MapView(this)
    setContentView(mapView)
    // mark gone immediately
    mapView.post {
      mapView.visibility = View.GONE
    }
    // verify that when marking it visible later - it works
    mapView.postDelayed(1_000L) {
      mapView.visibility = View.VISIBLE
    }
  }
```

**Comment by benferris-tl** [comment]
@kiryldz Thanks for looking into it. I think we're going to end up just consolidating the two `MapView`s into one and manipulating the camera to accomplish what we want.

**Comment by kiryldz** [comment]
@benferris-tl would be still curious if https://github.com/mapbox/mapbox-maps-android/issues/1570#issuecomment-1217940070 will work out for you. 
In any case, closing this as it's not actionable from our side.
