### ISSUE TITLE
Merging different annotation manager

### ISSUE THREAD

**Issue by tristan-garaud** [mapbox/mapbox-maps-android#1765]
## New Feature

Hi, I would like to be able to merge different annotation manager

## Why
I created a point annotation manager and I have a feature that is a polygon. I think I can transform it to a polygon annotation but even if I do that I would not be able to merge them. 
I want to merge them because I want to be able to decide where to put them in the z order (withSymbolSortKey).
But as they are separate entities I can't use the SymboleSortKey.
I don't know if there is a solution for that.
My polygon feature always display at the top.

Thanks

**Comment by ZiZasaurus** [comment]
@tristan-garaud, while there are no plans to support the merging of different annotation managers, each of these managers contains a sortKey property, however, In order to have all of your annotations sorted in the way you'd expect you will need to ensure that all of the geometries are located within one geojson.
