### ISSUE TITLE
How to detect click on a point on map created with source generation from Feature Collection

### ISSUE THREAD

**Issue by dimitradg** [mapbox/mapbox-maps-android#1870]
On my map, I load a style and then I add an image to it:

`style.addImage(
                    ICON_ID,
                    ContextCompat.getDrawable(requireContext(),
                        R.drawable.ic_location_point)
                        ?.toBitmap(12, 12)!!
)`

Afterwords, I use an ArrayList<Feature> to generate a source of Points and add it on style:

`style.addSource(
            geoJsonSource(SOURCE_ID) {
                featureCollection(FeatureCollection.fromFeatures(loadMarkers()))
            }
)`

*where loadMarkers returns an ArrayList<Feature>

Finally I add the symbol layer with the above mentioned image to the style for the specific source, in order to load this image on each point like a marker:

`style.addLayer(
            symbolLayer(LAYER_ID, SOURCE_ID){
                iconImage(ICON_ID)
                iconAllowOverlap(true)
                iconIgnorePlacement(true)
                textAllowOverlap(true)
                textField(Expression.get(MARKER_TITLE))
                textColor(Color.parseColor("#FF0000"))
                textJustify(TextJustify.CENTER)
                textSize(16f.toDouble())
                textAnchor(TextAnchor.TOP)
            }
        )`
        
What I would like to do is detect user's click on each point, like with OnPointAnnotationClickListener, get this point's information and perform several action. Is there any way to achieve that?

Is it preferable to load my markers with createPointAnnotationManager().create() rather than with style.addSource, to set a click listener?

Thank you in advance

**Comment by ZiZasaurus** [comment]
@dimitradg you can create a point annotation and set the image (instead of using a symbol layer) and then use the `onClickListener` to perform whatever actions you would like when the annotation is clicked.
Please note, it’s better and more convenient to use [createPointAnnotationManager](https://docs.mapbox.com/android/maps/api/10.9.1/mapbox-maps-android/com.mapbox.maps.plugin.annotation.generated/create-point-annotation-manager.html). For additional reference, please take a look at our PointAnnotationActivity example [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt).
