### ISSUE TITLE
PointAnnotation altitude is ignored

### ISSUE THREAD

**Issue by tukez** [mapbox/mapbox-maps-android#2160]
Altitude is ignored and the point annotation is always drawn on the ground level regardless of the altitude.

Also it would be nice if you could define the altitude reference for the point (either above ground level or above sea level). For example GPS gives the altitude as above sea level but other data sources might give the altitude in above ground level reference.

**Comment by pengdev** [comment]
Hey @tukez the point annotation is a 2D feature and it will always be drawn on the ground(surface of the map), This is expected behaviour. 

If you want to draw with altitude, please try with our ModelLayer and 3D models, there you could specify the [modelTranslation](https://docs.mapbox.com/android/maps/api/10.6.0/mapbox-maps-android/com.mapbox.maps.extension.style.layers.generated/-model-layer-dsl/model-translation.html).
