### ISSUE TITLE
View annotations blinking with SDK version 11.1.0

### ISSUE THREAD

**Issue by tisalmin** [mapbox/mapbox-maps-android#2263]
## Environment

- Android OS version: 14
- Devices affected: Emulator (not tested on real device) 
- Maps SDK Version: 11.1.0

## Observed behavior and steps to reproduce

View annotations blink on the map. Sometimes they are not shown at all. The behavior seems to change depending on the zoom level.

## Expected behavior

View annotations should not blink.

## Notes / preliminary analysis

Hard to say anything about the root cause. It could be that the user location marker and being close to the view annotations might have something to do with this.

## Additional links and references
This can be reproduces with the sample app given in issue #2240 

https://github.com/mapbox/mapbox-maps-android/assets/16644071/2c464117-5624-4b73-82b9-ed43724484ec

**Comment by zmiao** [comment]
Hi @tisalmin thanks for reporting this issue, actually this is expected behavior with the current implementation. 
As you can see when the orange emphasis circle radius extends to the View Annotation, the annotation gets disappears. Currently, the emphasis circle of the location indicator is also taken into account when checking the visibility of the view annotations.
In case you want the annotations to be persistent with the location indicator, you can set the ViewAnnotationOptions.allowOverlapWithPuck = false. This can also improve performance a little in case there would be a lot of view annotations on the screen.

**Comment by tisalmin** [comment]
With ViewAnnotationOptions.allowOverlapWithPuck = false  the view annotations cannot be seen at all.

**Comment by zmiao** [comment]
sorry, I made the wrong typing, I intend to suggest `true`. the default value of allowOverlapWithPuck is false, so if you want the annotation to be always visible, setting it to be true would be the correct option.
