### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for com.mapbox.common.location.LocationService

### ISSUE THREAD

**Issue by almosting** [mapbox/mapbox-maps-android#2302]
## Environment

- Android OS version: 8.1
- Devices affected:oppo r11
- Maps SDK Version:10.16.6

when use api LocationEngineProvider.getBestLocationEngine,app crash.

crash log:
 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for com.mapbox.common.location.LocationService com.mapbox.common.location.LocationServiceFactory.locationService() (tried Java_com_mapbox_common_location_LocationServiceFactory_locationService and Java_com_mapbox_common_location_LocationServiceFactory_locationService__)
E AndroidRuntime: 	at com.mapbox.common.location.LocationServiceFactory.locationService(Native Method)
E AndroidRuntime: 	at com.mapbox.common.location.compat.LocationEngineImpl.<init>(LocationEngineImpl.kt:32)
E AndroidRuntime: 	at com.mapbox.common.location.compat.LocationEngineProvider.getBestLocationEngine(LocationEngineProvider.kt:8)
E AndroidRuntime: 	at com.mapbox.android.core.location.LocationEngineProvider.getBestLocationEngine(LocationEngineProvider.java:44)
E AndroidRuntime: 	at com.link.ridermapbox.map.location.data.source.MapboxLocationDataSourceImpl.<init>(MapboxLocationDataSourceImpl.kt:34)
E AndroidRuntime: 	at com.link.ridermapbox.map.location.data.repository.LocationRepositoryImpl.<init>(LocationRepositoryImpl.kt:15)
E AndroidRuntime: 	at com.link.ridermapbox.map.MapManager.<init>(MapManager.kt:56)
E AndroidRuntime: 	at com.link.ridermapbox.api.RiderMap.init$ridermapbox_release(RiderMap.kt:46)

**Comment by jush** [comment]
Could you please share more details:
1. Please provide repro code if you can for us to test.
2. Are you removing the Mapbox initializers from the AndroidManifest?
3. Were there other crashes before this one?

Thanks

**Comment by kiryldz** [comment]
Additionally if you can reproduce it - please share the logs, thanks

**Comment by almosting** [comment]
this is my code：
    private val mLocationEngineRequest = LocationEngineRequest.Builder(DEFAULT_INTERVAL)
        .setPriority(LocationEngineRequest.PRIORITY_HIGH_ACCURACY)  
        .setDisplacement(DEFAULT_DISPLACEMENT)
        .setMaxWaitTime(DEFAULT_MAX_WAIT_TIME)
        .setFastestInterval(DEFAULT_FASTEST_INTERVAL) 
        .build()

    private val mLocationEngine: LocationEngine =
        LocationEngineProvider.getBestLocationEngine(application)

I use getBestLoactionEngine cause crash, other phone this problem will not occur。
[crash.log](https://github.com/mapbox/mapbox-maps-android/files/14534185/crash.log)

**Comment by jush** [comment]
@almosting does your app support direct boot mode? It seems that the crash happens while the device is still locked (i.e. user has not entered key lock, not even once)

**Comment by jush** [comment]
Another question, I see the crash happening in your `InitProvider`:
`com.link.ridermapbox.utils.InitProvider.onCreate(InitProvider.kt:23)`

Does your provider depend on the Mapbox providers?

**Comment by almosting** [comment]
my app dose not support direct boot mode，in my InitProvider，I use LocationEngineProvider.getBestLocationEngine，The strange thing is that only this phone has the problem

**Comment by kiryldz** [comment]
@almosting thanks for the logs. The root cause seems clear and is connected with your own initializer `com.link.ridermapbox.utils.InitProvider` being run before initializers we have in our SDK and at the same time accessing methods from Mapbox SDK in `InitProvider`. If you're using AndroidX startup [initializers](https://developer.android.com/topic/libraries/app-startup) to do that you should guarantee that our Mapbox initializers are run before `com.link.ridermapbox.utils.InitProvider`. This could be achieved with declaring our initializer as a dependency:

```
// code for your com.link.ridermapbox.utils.InitProvider
class InitProvider: Initializer<Something> {
 
  ...
 
  override fun dependencies(): List<Class<out Initializer<*>>> {
        return listOf(MapboxMapsInitializerImpl::class.java)
  }

}
```

If you somehow are not using AndroidX startup initializers and using some other solution to execute code on startup - I'd say the easiest solution would be to still add AndroidX startup as a dependency and trigger `MapboxMapsInitializerImpl` [programatically](https://developer.android.com/topic/libraries/app-startup#manual-initialization) before accessing any Mapbox SDK methods.
