### ISSUE TITLE
PointAnnotations disappear/reappear depending on zoom level

### ISSUE THREAD

**Issue by brendanw** [mapbox/mapbox-maps-android#2313]
## Environment

- Android OS version: Android 34
- Devices affected: Pixel 5
- Maps SDK Version: 11.3.0-beta.1

## Observed behavior and steps to reproduce

After applying a filter that impacts the data source for a `PointAnnotationGroup`, `PointAnnotation` visibility does not persist, individual `PointAnnotation`s disappear and re-appear depending on zoom level.

See screen recording at https://brendanw.s3.us-west-2.amazonaws.com/pointAnnotationIssue.mov

I didn't have this issue before switching to using the compose extension.

## Expected behavior

PointAnnotation visibility should not change based on zoom level

## Notes / preliminary analysis

Here is my compose extension usage
```kotlin
         val shouldDisplayExits = AppDependencies.mapModel.shouldDisplayExits.collectAsState().value
         if (shouldDisplayExits) {
            val exits = AppDependencies.mapModel.exits.collectAsState()
            val points = remember(exits.value) {
               if (exits.value == null) {
                  return@remember emptyList()
               } else {
                  exits.value!!.map { exit -> createPointAnnotationOption(exit) }
               }
            }

            PointAnnotationGroup(
               annotations = points,
               onClick = { pointAnnotation ->
                  val data = pointAnnotation.getData()
                  if (data?.isJsonNull == true || data == null) {
                     return@PointAnnotationGroup false
                  }

                  val jsonObject = data.asJsonObject ?: return@PointAnnotationGroup false
                  val exitId = jsonObject.get("exitId").asString ?: return@PointAnnotationGroup false
                  val exitName = jsonObject.get("exitName").asString ?: return@PointAnnotationGroup false
                  val isExitVerified = jsonObject.get("isExitVerified").asBoolean
                  lastViewAnnnotationOpen.value = Clock.System.now().toEpochMilliseconds()
                  AppDependencies.mapModel.openViewAnnotation(
                     exitId = exitId,
                     text = exitName,
                     latitude = pointAnnotation.point.latitude(),
                     longitude = pointAnnotation.point.longitude(),
                     profileId = null,
                     isVerified = isExitVerified,
                     dropzoneId = null
                  )

                  true
               }
            )
         }
         
private fun createPointAnnotationOption(exit: MapExit): PointAnnotationOptions {
   val element = JsonObject()
   element.addProperty("exitId", exit._id)
   element.addProperty("exitName", exit.name)
   element.addProperty("isExitVerified", exit.isExitVerified)
   val option = PointAnnotationOptions()
      .withPoint(Point.fromLngLat(exit.longitude, exit.latitude))
      .withIconImage("blue-pin")
      .withData(element)
   return option
}
```

**Comment by pengdev** [comment]
@brendanw from the video, it looks like the somehow the [iconAllowOverlap](https://docs.mapbox.com/android/maps/api/11.2.2/mapbox-maps-android/com.mapbox.maps.extension.compose.annotation.generated/-point-annotation-group.html?query=fun%20PointAnnotationGroup(annotations:%20List%3CPointAnnotationOptions%3E,%20annotationConfig:%20AnnotationConfig?%20=%20null,%20iconAllowOverlap:%20Boolean?%20=%20null,%20iconIgnorePlacement:%20Boolean?%20=%20null,%20iconKeepUpright:%20Boolean?%20=%20null,%20iconOptional:%20Boolean?%20=%20null,%20iconPadding:%20Double?%20=%20null,%20iconPitchAlignment:%20IconPitchAlignment?%20=%20null,%20iconRotationAlignment:%20IconRotationAlignment?%20=%20null,%20symbolAvoidEdges:%20Boolean?%20=%20null,%20symbolPlacement:%20SymbolPlacement?%20=%20null,%20symbolSpacing:%20Double?%20=%20null,%20symbolZElevate:%20Boolean?%20=%20null,%20symbolZOrder:%20SymbolZOrder?%20=%20null,%20textAllowOverlap:%20Boolean?%20=%20null,%20textFont:%20List%3CString%3E?%20=%20null,%20textIgnorePlacement:%20Boolean?%20=%20null,%20textKeepUpright:%20Boolean?%20=%20null,%20textMaxAngle:%20Double?%20=%20null,%20textOptional:%20Boolean?%20=%20null,%20textPadding:%20Double?%20=%20null,%20textPitchAlignment:%20TextPitchAlignment?%20=%20null,%20textRotationAlignment:%20TextRotationAlignment?%20=%20null,%20textVariableAnchor:%20List%3CString%3E?%20=%20null,%20textWritingMode:%20List%3CString%3E?%20=%20null,%20iconColorSaturation:%20Double?%20=%20null,%20iconTranslate:%20List%3CDouble%3E?%20=%20null,%20iconTranslateAnchor:%20IconTranslateAnchor?%20=%20null,%20textTranslate:%20List%3CDouble%3E?%20=%20null,%20textTranslateAnchor:%20TextTranslateAnchor?%20=%20null,%20onClick:%20(PointAnnotation)%20-%3E%20Boolean%20=%20{%20false%20})) behaves like it was disabled, could you try to manually set it to true?

Please also note there's a known issue regarding applying `AnnotationGroup` properties, which is fixed in 11.3.0-rc.1 release, please update to the latest version and try again.

**Comment by brendanw** [comment]
I am still seeing the issue with setting `iconAllowOverlap=true` on the `PointAnnotationGroup` and using `11.3.0-rc.1`

**Comment by pengdev** [comment]
@brendanw could you also try with setting `iconIgnorePlacement = true`?

**Comment by brendanw** [comment]
I am still seeing the issue with setting `iconIgnorePlacement = true` on the `PointAnnotationGroup` and using `11.3.0-rc.1`

**Comment by pengdev** [comment]
@brendanw could you please provide a minimal project to reproduce the issue? maybe a patch to our existing [compos-app](https://github.com/mapbox/mapbox-maps-android/tree/main/compose-app/src/main/java/com/mapbox/maps/compose/testapp/examples/annotation) example app would be really helpful.

**Comment by brendanw** [comment]
https://github.com/brendanw/MapboxMemLeak/tree/bw/pointAnnotationIssue

^^ Can reproduce the issue by running the code on the `pointAnnotationIssue` branch. Just need to populate `MAPBOX_SECRET_TOKEN` environment variable before running.

I am reusing an older reproducer project for this, but here's the minimal diff for reproducing the issue -> https://github.com/brendanw/MapboxMemLeak/pull/2

With regard to the compose example app, I tried to use the compose-app example app. I populated SDK_REGISTRY_TOKEN and could get the application running, but the map screens all rendered black.

**Comment by pengdev** [comment]
@brendanw sorry didn't have time to try your branch earlier, I dropped a comment in your branch and with iconAllowOverlap=true set to the PointAnnotationGroup, I do see the issue being resolved, please let me know if you have other issues.

**Comment by brendanw** [comment]
@pengdev I am an idiot. I have multiple PointAnnotationGroup's for the screen this is on and I neglected to add this field to one of those groups. Thanks for bearing with me and apologies for the false report!
