### ISSUE TITLE
[compose] MapInitOptions doesn't fully load styleUri

### ISSUE THREAD

**Issue by GioraGit** [mapbox/mapbox-maps-android#2334]
## Environment

- Android OS version: 30
- Devices affected: Pixel 4
- Maps SDK Version: 11.3.0-rc.1

## Observed behavior and steps to reproduce

When I updated mapbox from 11.1.0 to 11.3.0-rc1 I noticed that the style I was using before (the one in the `styleUri` bellow) wasn't now fully loaded onto the map. Specifically the background/surface of the map was different. It seems like the `Style.STANDARD` one, not mine. Beside updating the library I didn't do anything else. The following code is the one that is used in both versions of the library, but with different results regarding the map visual style.
```
MapboxMap(
        mapInitOptionsFactory = { context ->
            MapInitOptions(
                context = context,
                styleUri = "mapbox://styles/climacell/cjx91l1u41my01dl71kd3w261",
                cameraOptions = cameraOptions {
                    center(Point.fromLngLat(0.0, 0.0))
                    zoom(6.5)
                }
            )
        },,
    ) {...}
```

Here is my expected map (the dark one, which used to work):

![image](https://github.com/mapbox/mapbox-maps-android/assets/22842512/d82af1ef-c1b4-4152-b666-8bbd62c3b756)

And here is the current result (seems like standard):

![image](https://github.com/mapbox/mapbox-maps-android/assets/22842512/698d9412-cdb0-4159-9672-94c2f3649c9b)

## Expected behavior

It should have work like previous versions, i.e my style should be loaded.

## Notes / preliminary analysis

I noticed the bug started to happen since v11.3.0-beta.1. Up until v11.2.2 all is good.

I also noticed that with the latest version (11.3.0-rc.1), if I add the following in the `content` of `MapboxMap()`, the standard "light" map is initially loaded, but then my style is correctly loaded:

```
        MapEffect(Unit) {
            it.mapboxMap.loadStyle("mapbox://styles/climacell/cjx91l1u41my01dl71kd3w261")
        }
```

## Additional links and references

I didn't see anything about this in the docs/changelog.

**Comment by pengdev** [comment]
@GioraGit please checkout our latest release https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0 
There are several breaking changes for the experimental compose extension:
*  We have introduced style composable functions since 11.3.0-rc.1, the new style composable functions will overwrite the style defined `mapInitiOptionsFactory` 
* In 11.3.0 we replaced the `mapInitOptionsFactory` with `composeMapInitOptions`, with the conflicting properties like style and camera options removed. 

Please use style composable functions and mapViewportStates to handle mapbox style and camera in compose extension.

Your code snippets can be changed to something like:

```
MapboxMap(
    mapViewportState = MapViewportState().apply {
      setCameraOptions {
        center(Point.fromLngLat(0.0, 0.0))
        zoom(6.5)
      }
    },
    style = {
      MapStyle(style = "mapbox://styles/climacell/cjx91l1u41my01dl71kd3w261")
    }
) {...}
```

**Comment by GioraGit** [comment]
Thank you @pengdev , that did the trick 👍
