### ISSUE TITLE
Update existing features in a GeoJSON style source not working

### ISSUE THREAD

**Issue by SigmaAppdevelopment** [mapbox/mapbox-maps-android#2517]
## Environment

- Android OS version: 34
- Maps SDK Version: 11.5.1

## Observed behavior and steps to reproduce

Hi, we have a symbollayer with geoJsonSource. We want to update position (geometry) of this layer every second. So we add geometry-feature with addGeoJsonSourceFeatures and update with updateGeoJsonSourceFeatures. See code below.

```
fun initMarker() {
	val markerSource = geoJsonSource("currentMarkerSource")
	markerSource.addGeoJSONSourceFeatures(
   		listOf(
    		 Feature.fromGeometry(
         		Point.fromLngLat(0.0, 0.0),
         	   	null,
         	   	"geoId"
     		 ),
   		)
	)
	style.addSource(markerSource)
}
```

```
fun updateMarker(point: Point) {
	val feature = Feature.fromGeometry(point, null, "geoId")
	val locationSource = style.getSource("currentMarkerSource") as? GeoJsonSource
	locationSource?.updateGeoJSONSourceFeatures(features)
}
```

Mapbox returns error:
Error: [maps-core]: {}[Style]: Failed to load source currentMarkerSource: Cannot create new geojson impl for Update/Remove feature operations

What are we missing? Also tried to set dataId on addGeoJsonSourceFeature and updateGeoJsonSourceFeature, but didn't help. Couldn't find an example.

**Comment by iolandarosavoid** [comment]
I am also unsure why the code above does not work when it seems to be ok.

Anyway I will also be waiting for the mapbox team response but in the meanwhile let me leave you here an alternative solution that should work:
```

**Comment by iolandarosavoid** [comment]
Hello.

I also don't understand why your code does not work, but maybe an alternative solution might be helpful. It is very similar to what you have implemented but using the FeatureCollection instead of the feature array directly.

```
fun addOrUpdateSource(style: Style, collection: FeatureCollection, sourceId: String) {
        val source = style.getSource(sourceId) as? GeoJsonSource?
        if (source == null) {
            style.addSource(
                geoJsonSource(sourceId).apply {
                    featureCollection(collection)
                },
            )
        } else {
            source.featureCollection(collection)
        }
    }
```

To get the `FeatureCollection` you just use the method `FeatureCollection.fromFeatures(<your_features_array>)` and this way it should be fine.

Anyway I finding some weird bugs on source data update specially using the compose version of mapbox. I always have to use old methods because updates of GeoJSONData in compose source are very buggy. I don't get it

**Comment by SigmaAppdevelopment** [comment]
Hello,

yes, what you suggest works. But we wanted to use new api because it should be much more performant...
