### ISSUE TITLE
Configuration to disable all gestures

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#40]
While we expose granular control over enabled/disabling gestures. We don't expose a main kill switch to disable them all.
Above matches the following sequence:

```
    val gesturesPlugin = mapView.getGesturesPlugin()
    gesturesPlugin.pitchEnabled = false
    gesturesPlugin.rotateEnabled = false
    gesturesPlugin.zoomEnabled = false
    gesturesPlugin.scrollEnabled = false
    // since this issue was created we have a couple more enabled properties   
    // and renamed a couple properties as well
```

 - tests
 - add API
 - add integration example in gestures activity
 - ~~serialisation spec?~~ -> needs discussion, maybe just as extension function
 - validate naming from OP with current state

**Comment by kiryldz** [comment]
Stale, outdated. Personal note: this API is questionable because if you need a map without any interactions, we have dedicated Snapshotter API to capture a static snapshot of the map. Another point: disabling all the interactions seems to be equivalent to calling 4 methods in this issue description so does not seem that hard.
