### ISSUE TITLE
Animating MapView when resizing

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#440]
## Environment

- Android OS version: 11
- Devices affected: Samsung Galaxy Tab S7, Samsung Galaxy Tab S20+
- Maps SDK Version: 10.0.0-rc.1

See screen recording:

https://user-images.githubusercontent.com/19756326/122711966-b5622400-d295-11eb-8324-8e16934b812c.mp4

How do we improve the animation when resizing the MapView so that it looks smoother and there are no black bars?

**Comment by cramptonism** [comment]
Have you tried positioning the map under the drawer and using EdgeInsets to define the visible portion of the MapView?

**Comment by tobrun** [comment]
@VincentJoshuaET the default implementation of MapView uses a SurfaceView. If you want to animate the MapView, you can use a TextureView instead of a SurfaceView. This type of View is more optimized for these type of use-cases. 
This can either be enabled programatically with:
 -  https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt#L30
or using an xml configuraiton:
 - `mapbox_mapSurface` https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/res/layout/activity_texture_view.xml#L8
