### ISSUE TITLE
3D Terrain not rendering anymore

### ISSUE THREAD

**Issue by alexandre-pereira** [mapbox/mapbox-maps-android#443]
## Environment

- Android OS version: 11
- Devices affected: Redmi K20 PRO
- Maps SDK Version: RC1

## Observed behavior and steps to reproduce
Enable 3D Terrain in mapbox studio
-> Not rendering anymore since RC1

## Expected behavior
rendering correctly

**Comment by kiryldz** [comment]
@alexandre-pereira could you please provide more information (and better a code snippet) how are you loading a style with terrain? As per description it seems that you've created the style in Mapbox Studio and trying to load it with Android SDK but would like you to confirm it.
You could also try loading style with terrain the way it's done [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/terrain/Terrain3DShowcaseActivity.kt) to make sure this problem is not related to your hardware.

**Comment by alexandre-pereira** [comment]
Yes, that's it. I'm using Java language and RC1. Didn't had this bug with the previous beta version. I'll try this way and let you know, but still the bug is here.

**Comment by kiryldz** [comment]
@alexandre-pereira I've reproduced this issue. This will be fixed in upcoming `v10.0.0-rc.3` release in several weeks. Meanwhile as workaround you could prepare your style without terrain in Studio and add it programatically similar to the way it's done [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/terrain/Terrain3DShowcaseActivity.kt).

**Comment by kiryldz** [comment]
@alexandre-pereira [rc.3](https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.0.0-rc.3) release has just landed, issue should be fixed there, closing.
