### ISSUE TITLE
Location Plugin should not be deprecated until the new plugin is available.

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#54]

**Comment by tobrun** [comment]
Hello @VincentJoshuaET, thank you for reaching out and providing feebdack! We are currently in beta phase and aren't going stable for some months. The reason why we deprecated [the old approach](https://github.com/mapbox/mapbox-maps-android/tree/main/plugin-location) was to be very intentional to our users it's going away and will be replaced with [the new approach](https://github.com/mapbox/mapbox-maps-android/tree/main/plugin-locationcomponent). 

Thank you for reporting but for us this issue isn't actionable atm. Closing
