### ISSUE TITLE
GestureSettings is missing the option to disable 'shoveGestures'

### ISSUE THREAD

**Issue by AndreasBoehm** [mapbox/mapbox-maps-android#578]
## New Feature

The gesture plugin should offer the option to disable `shoveGestures`.

File:
https://github.com/mapbox/mapbox-maps-android/blob/main/sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt

## Why
I don't want my users to be able to use shove gestures.
Right now I can only disable `shoveGestures` by removing the `ShoveGesturesListener`
```
mapboxMap.getGesturesManager()?.removeShoveGestureListener()
```

**Comment by pengdev** [comment]
Hi @AndreasBoehm , the shove gesture detects a vertical movement of two pointers if they are placed within a certain horizontal angle. This gesture will affect the camera pitch, so if you want to disable camera pitch caused by the shove gesture, you can set the `mapView.gestures.pitchEnabled = false`.

**Comment by AndreasBoehm** [comment]
Thank you @pengdev, `pichEnabled = false` is working perfectly fine.
