### ISSUE TITLE
Improve "Failed to load style: Chain validation failed" error when style can not be loaded due to wrong date time set

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-maps-android#585]
Hey folks,

I spent an embarrassingly long time trying to figure out why my map stayed all black when it was working perfectly on Friday.

> E/maps: {io.ruumi.graze}[Setup]: Failed to load style: Chain validation failed
> E/Mbgl-StyleObserver: OnMapLoadError: STYLE: Failed to load style: Chain validation failed

These were the only error messages I could see in the logs.

Turns out for some reason (still not sure why) my emulator's phone date time was still stuck on Friday (today is Monday), and then the map style can not be loaded because the certificate fails to validate.

It would be great to
- either detect the situation and show a more specific error message, or
- at least show a hint like "is your date time set correctly?" to make debugging this easier

That's all! Thanks.

**Comment by kiryldz** [comment]
This relates to development on emulators in specific situations. Although I like your suggestion but that will require patching really low-level components of our SDK(s) and most likely will not be done because of pretty minor business impact. The good thing that users facing the same can go to this repo and find this issue with the solution! Updated the description.
