### ISSUE TITLE
Documentation or samples for persistent layers

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#662]
Hi,

yesterday i looked into using the `addPersistentLayer` functionality. It works already with my custom layers that use a `CustomLayerHost`and are added via `addPersistentStyleCustomLayer`. However i think the behaviour is a bit strange.

I need to add the persistent layer again on every style load. It is immediately displayed on style reload, so that already improved (which i guess was the goal of that API). Before it shortly disappeared and reappeared. However i find it a bit strange, that i have to add persistent layers over and over again. In my opinion it would make more sense to add them once, and then they are reused automatically on each style reload.

For example right now i add them like this:
```
 mapboxMap.addOnStyleLoadedListener(() -> {
  mapboxMap.getStyle().addPersistentStyleCustomLayer("soc-overlay-layer", socOverlay, overlayLayerPosition);
  mapboxMap.getStyle().addPersistentStyleCustomLayer("charger-overlay-layer", chargerOverlay, overlayLayerPosition);
  mapboxMap.getStyle().addPersistentStyleCustomLayer("speedlimit-overlay-layer", speedlimitOverlay, overlayLayerPosition);
});
```

The other problem i face is that when i use a layer with a `GeoJsonSource`, i get errors when the data of the `GeoJsonSource` changes while the style reloads. It complains about the `GeoJsonSource` not being part of a style. That is rather strange as well, as i think the `GeoJsonSource`could actually get new data already, even if it is not part of a style. But that is another problem and unrelated to persistent layer. My question to that regard is, will this problem be solved when using a persistent layer? Can i then update the `GeoJsonSource`even when the style reloads? If so how do i have to do it, as the `GeoJsonSource`also needs to be added to the style every time...

Best
Samuel

**Comment by SamuelBrucksch** [comment]
Ok i got it to work now with the persistent layers. However the behaviour does not seem to be the same as with the CustomLayers. CustomLayers need to be added each time again, the normal layers crash the app if they are added agin, so they indeed seem to be cached. same for the sources. I guess this discrepancy is not intended, is it?

**Comment by SamuelBrucksch** [comment]
@pengdev i think you worked on persistent layers, maybe you could comment on this? If i add a persistent Layer via `addPersistentStyleCustomLayer` i need to add it again on each style reload, but if i add one via `addPersistentLayer` it only needs to be done once.

**Comment by alexshalamov** [comment]
@SamuelBrucksch thank you for the report! I quickly modified test application and can't reproduce the issue. Would be nice to get second 👀 from Android team.

```diff
diff --git a/app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/CustomLayerActivity.kt b/app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/CustomLayerActivity.kt
index 5c31de3e..f0e496a1 100644
--- a/app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/CustomLayerActivity.kt
+++ b/app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/CustomLayerActivity.kt
@@ -31,31 +31,35 @@ class CustomLayerActivity : AppCompatActivity() {
       mapboxMap.setCamera(
         CameraOptions.Builder().center(Point.fromLngLat(116.39053, 39.91448)).zoom(10.0).build()
       )
+      val expected = it.addPersistentStyleCustomLayer(
+        layerId = CUSTOM_LAYER_ID,
+        ExampleCustomLayer(),
+        LayerPosition(null, "building", null)
+      )
+      expected.error?.let {
+        Logger.e(TAG, "Add custom layer exception $it")
+      }
+
       initFab()
     }
   }

   private fun initFab() {
     binding.fab.setOnClickListener {
-      swapCustomLayer()
+      swapStyles()
     }
   }

-  private fun swapCustomLayer() {
+  private fun swapStyles() {
     mapboxMap.getStyle()?.let { style ->
-      if (style.styleLayerExists(CUSTOM_LAYER_ID)) {
-        style.removeStyleLayer(CUSTOM_LAYER_ID)
-        binding.fab.setImageResource(R.drawable.ic_layers)
+      if (style.styleURI.equals(Style.MAPBOX_STREETS)) {
+        mapboxMap.loadStyleUri(
+          Style.DARK
+        )
       } else {
-        val expected = style.addStyleCustomLayer(
-          layerId = CUSTOM_LAYER_ID,
-          ExampleCustomLayer(),
-          LayerPosition(null, "building", null)
+        mapboxMap.loadStyleUri(
+          Style.MAPBOX_STREETS
         )
-        expected.error?.let {
-          Logger.e(TAG, "Add custom layer exception $it")
-        }
-        binding.fab.setImageResource(R.drawable.ic_layers_clear)
       }
     }
   }
```

**Comment by SamuelBrucksch** [comment]
Hi,

thanks for your check. I modified my code a bit since yesterday. Due to JAVA - Kotlin compatibility problems i used a Kotlin helper class and a `StyleExtension` to have minimum code in Kotlin (we use JAVA mainly). So it might have been related to the `StyleExtension`.

Now i'm modifying the style directly and don't use a `StyleExtension` anymore and it seems to work. So the problem does not exist anymore.

Still i would propose to add some sample code so it is easier to understand how it works. Also from Java some functions are missing. For example `addPersistentStyleLayer` requires a `Value` instead of a Layer like the same function in Kotlin.

Best
Samuel

**Comment by pengdev** [comment]
Hi @SamuelBrucksch thanks for trying out the persistent layer. The `persistentLayer` and `persistentCustom` Layer APIs are experimental APIs and are currently only used internally. They might introduce some side effects when used with sources from different Styles etc, so you should be careful when using it in your application.

Thanks @alexshalamov for the validation, I think the `addPersistentCustomLayer` should work as expected. 

> Now i'm modifying the style directly and don't use a StyleExtension anymore and it seems to work. So the problem does not exist anymore.

StyleExtension provides a set of high level APIs for manipulating the style, under the hood, it uses the low level style APIs with generic `Value` type. As you noticed, the style extension takes advantage of some convenient Kotlin language features to support things like Style DSL. By nature Kotlin is compatible with Java and we also did some improvements to the Jvm signatures to make it more Java-friendly. That said, many functions in style extension are Kotlin extension functions, that means in order to use it in Java, you would need to use the generated static utils, for example to add a persistent layer, you could do the following:
```
LayerUtils.addPersistentLayer(style, layer, layerPosition);
```

> Still i would propose to add some sample code so it is easier to understand how it works. Also from Java some functions are missing or have the wrong signature. For example addPersistentStyleLayer requires a Value instead of a Layer like the same function in Kotlin.

And the StyleExtension doesn't work with `CustomLayer` at the moment, since Custom layer requires user to handle the Open-Gl drawing instead of just providing some style properties like the other layer types.  We currently only have low level API for custom layer. So the `addPersistentStyleLayer` would require the use of the generic `Value` type.

And we are also working on a Style and Expressions guide for v10, will provide more context there as well.
