### ISSUE TITLE
Over-zoom causes some layers to render underground when terrain/3D is enabled

### ISSUE THREAD

**Issue by e-hartig** [mapbox/mapbox-maps-android#789]
## Environment

- Android OS version: 
- Devices affected:
- Maps SDK Version: Have seen this in 10.0.0-rc.3 - 10.1.0-beta.1

## Observed behavior and steps to reproduce

With terrain enabled, when a map source has a low max zoom set and the camera is zoomed in past that point, some layers render below the ground (perhaps at sea level).  This is especially apparent in road and place labels that don't align properly when the map is pitched.

To reproduce:
1.  Add this parameter to the call to `mapboxMap.loadStyle` in Terrain3DShowcaseActivity in the mapbox test app:
```
      onStyleLoaded = {
        it.setStyleSourceProperty("composite", "maxzoom", Value.valueOf(12.0))
      }
```
2. Run the app
3. Pan to a relatively low-elevation area with some POIs and roads
4. Zoom in pretty far (higher than zoom 12)
5. Change bearing or pitch to observe that some labels are rendering underground

## Expected behavior

All layers for a map source should be properly overlaid on the terrain no matter what its max zoom is.

## Additional links and references
The road labels for 468 and the temple label are affected in this screen cap from the mapbox sample app:

https://user-images.githubusercontent.com/71792506/139467581-75b0dbb7-cb90-4e64-9678-704738832861.mov

**Comment by astojilj** [comment]
@e-hartig,

```
      onStyleLoaded = {
        it.setStyleSourceProperty("composite", "maxzoom", Value.valueOf(12.0))
      }
```

It is an implementation constraint (it is a bug logged in https://github.com/mapbox/mapbox-gl-js/issues/10265), that vector source needs to be of higher zoom level than terrain's raster- dem source. As a matter of fact, it is so that in common case, composite of zoom 16 is using raster-dem tile, size 514x514 of zoom level 13 or 14 by sampling and interpolating elevation from a sub-tile of raster-dem tile. Symbols are elevated over terrain on GPU, by sampling raster dem texture.

So, in this case, if specifying max zoom of 12 for raster DEM, suggest to use max zoom of 11 or 10 for raster DEM.
I believe that would be valid workaround and help with the specific issue, although used raster-dem would be of lower resolution.

**Comment by juloaiza** [comment]
What is the status about this issue?

**Comment by astojilj** [comment]
@juloaiza 

Thanks for checking. It has low priority since it is assumed that it is easy to incorporate the workaround https://github.com/mapbox/mapbox-maps-android/issues/789#issuecomment-956435740.
> it.setStyleSourceProperty("composite", "maxzoom", Value.valueOf(12.0))
Could you also try setting source max zoom to higher value but
