### ISSUE TITLE
Annotation drag does not work after setting isDraggable true in OnLongClickListener

### ISSUE THREAD

**Issue by dimysa** [mapbox/mapbox-maps-android#928]
## Environment

- Android OS version: 11
- Devices affected: OnePlus 8 Pro
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce

If set `annotation.isDraggable = true` in LongClickListeners callback (`AnnotationPlugin.addLongClickListener`), isDraggable will not be enabled, and we cannot drag the annotation. This works correctly in v9 plugin.

## Expected behavior

We can drag the annotation after enable draggable in `onAnnotationLongClick`.

## Notes / preliminary analysis

Looks like `onMoveBegin` called early then `onMapLongClick`, and so `draggingAnnotation` is null, because `startDragging` ignore set `draggingAnnotation` if isDraggable = false [source code](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L703) 

## Additional links and references

Source code example : https://gist.github.com/dimysa/2c057aa88cdbe2065663e3f80517d73d

**Comment by kiryldz** [comment]
cc @Chaoba

**Comment by ank27** [comment]
@dimysa I tested with the source code you provided, it seems the drag is working as expected. (Check the attached video)
you can also refer to the [example activity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt) for more reference

https://user-images.githubusercontent.com/11589497/144070236-7cd8c8d2-92d6-4082-b197-fb12f661b1f3.mp4

**Comment by Chaoba** [comment]
After change the `isDraggable` property, you must call `update` method. 
`pointAnnotationManager.update(annotation)`

**Comment by dimysa** [comment]
@ank27
It looks interesting because it works on emulators (Android 9, 10 and 11), but it doesn't work on my phone (OnePlus 8 pro - Android 11)
https://user-images.githubusercontent.com/14176511/144080829-f7147a3f-42da-4dc6-ab83-364461fb3e04.mp4

**Comment by dimysa** [comment]
I noticed that if I try to repeat this using [scrcpy](https://github.com/Genymobile/scrcpy) and control the phone with the mouse (the device will show up on my computer), the bug does not reproduce. I also subscribed to the `onMoveListener` (`mapView.gestures.addOnMoveListener`) and noticed that i I hold my finger long on the screen (over the annotation or just over the map) `onMoveBegin` will be called. However, if you do it with the mouse (via scrcpy, as I described above), then `onMoveBegin` is not called

**Comment by Chaoba** [comment]
`onMoveBegin` are triggered before `onMapLongClick`, which means you are changing the `isDraggable` during the move gesture. So, IMHO it is hard to say this is a bug.

**Comment by dimysa** [comment]
but I don't move my finger, `onMoveBegin` shouldn't be called at all. I started the issue because I found a mismatch between versions 9 and 10 of the library

**Comment by jenz0rw00t** [comment]
+1. 
I was using this way of handling draggable annotations before on v9 and can confirm that it doesn't work on v10 on any phones i have tested (and that it worked without any issues on v9). I found this to be the only way to handle annotations that needed to be clickable as well as draggable since that experience is not good with how `isDraggable` works.

**Comment by Chaoba** [comment]
Fix in https://github.com/mapbox/mapbox-maps-android/pull/990

**Comment by jenz0rw00t** [comment]
@Chaoba Sorry for the late reply!
Haven't looked into this more until now but this is still an issue for me. It works on the emulator since with a mouse or trackpad you are able to hold the pointer completely still but on a real device it is impossible to not move the pointer at all (causing a `startDragging()` to happen). 
I would consider this currently still an issue since being able to drag a waypoint after a longpress was working before v9 and is also currently working in the most recent mapbox iOS SDK, causing disparity between libraries.

**Comment by evkirby** [comment]
+1
@jenz0rw00t did you ever find a workaround for this? I am also running into the same issue when setting `isDraggable` to true when starting a long press (using Mapbox Android SDK v10.11.0). The expected behaviour also works on emulators, for the same reason you described. 

My goal is to require the user to long press on annotations before dragging them, but it seems that setting `isDraggable` to true after a long press starts is too late.

**Comment by dimysa** [comment]
the following code can be used as a workaround 
```
val gestureManager = map.gestures.getGesturesManager()
gestureManager.moveGestureDetector.interrupt()
```
after you set `isDraggable = true`.
It doesn't look like a nice solution, but it seems to work

**Comment by evkirby** [comment]
Thank you @dimysa! Your workaround does seem to work in my case! 😄
